language: java
sudo: false

matrix:
  include:
    # Headed Linux
    - os: linux
      dist: trusty
      jdk: oraclejdk9
    # Headless Linux
    - os: linux
      dist: trusty
      jdk: oraclejdk9
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

addons:
  apt:
    packages:
      - oracle-java9-installer

before_install:
  - mvn install:install-file -Dfile=TestProjekt/tmpBin/common-1.0-SNAPSHOT.jar -DgroupId=com.github.mitschi -DartifactId=common -Dversion=1.0-SNAPSHOT -Dpackaging=jar
  - mvn install:install-file -Dfile=TestProjekt/tmpBin/maven-buildfix-1.0-SNAPSHOT.jar -DgroupId=com.github.mitschi -DartifactId=maven-buildfix -Dversion=1.0-SNAPSHOT -Dpackaging=jar
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

install: true
    
script:
  - cd TestProjekt
  - mvn clean install
  
after_success:
  - bash <(curl -s https://codecov.io/bash)